name: Deploy to GitHub Pages

on:
  push:
    branches: [ test-deploy ]  # Активируется при push в main ветку

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Restore dependencies
      run: npm install
      
    - name: Publish project
      run: npm run build

    - name: Add .nojekyll
      run: touch dist/.nojekyl
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist
        enable_jekyll: false  
        keep_files: false     
        force_orphan: true